// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostAddrRequset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addres        string                 `protobuf:"bytes,1,opt,name=addres,proto3" json:"addres,omitempty"` // адрес для сокращения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAddrRequset) Reset() {
	*x = PostAddrRequset{}
	mi := &file_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAddrRequset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAddrRequset) ProtoMessage() {}

func (x *PostAddrRequset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAddrRequset.ProtoReflect.Descriptor instead.
func (*PostAddrRequset) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *PostAddrRequset) GetAddres() string {
	if x != nil {
		return x.Addres
	}
	return ""
}

type PostAddrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addres        string                 `protobuf:"bytes,1,opt,name=addres,proto3" json:"addres,omitempty"` // адрес для сокращения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAddrResponse) Reset() {
	*x = PostAddrResponse{}
	mi := &file_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAddrResponse) ProtoMessage() {}

func (x *PostAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAddrResponse.ProtoReflect.Descriptor instead.
func (*PostAddrResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *PostAddrResponse) GetAddres() string {
	if x != nil {
		return x.Addres
	}
	return ""
}

type GetAddrRequset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortAddr     string                 `protobuf:"bytes,1,opt,name=shortAddr,proto3" json:"shortAddr,omitempty"` // короткий адрес
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddrRequset) Reset() {
	*x = GetAddrRequset{}
	mi := &file_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddrRequset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddrRequset) ProtoMessage() {}

func (x *GetAddrRequset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddrRequset.ProtoReflect.Descriptor instead.
func (*GetAddrRequset) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddrRequset) GetShortAddr() string {
	if x != nil {
		return x.ShortAddr
	}
	return ""
}

type GetAddrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addres        string                 `protobuf:"bytes,1,opt,name=addres,proto3" json:"addres,omitempty"` // длинный адрес
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddrResponse) Reset() {
	*x = GetAddrResponse{}
	mi := &file_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddrResponse) ProtoMessage() {}

func (x *GetAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddrResponse.ProtoReflect.Descriptor instead.
func (*GetAddrResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetAddrResponse) GetAddres() string {
	if x != nil {
		return x.Addres
	}
	return ""
}

type UserURLs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrigURL       string                 `protobuf:"bytes,1,opt,name=origURL,proto3" json:"origURL,omitempty"`
	ShortURL      string                 `protobuf:"bytes,2,opt,name=shortURL,proto3" json:"shortURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLs) Reset() {
	*x = UserURLs{}
	mi := &file_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLs) ProtoMessage() {}

func (x *UserURLs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLs.ProtoReflect.Descriptor instead.
func (*UserURLs) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *UserURLs) GetOrigURL() string {
	if x != nil {
		return x.OrigURL
	}
	return ""
}

func (x *UserURLs) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

type GetAddrUserRequset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddrUserRequset) Reset() {
	*x = GetAddrUserRequset{}
	mi := &file_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddrUserRequset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddrUserRequset) ProtoMessage() {}

func (x *GetAddrUserRequset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddrUserRequset.ProtoReflect.Descriptor instead.
func (*GetAddrUserRequset) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{5}
}

type GetAddrUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserURLs      []*UserURLs            `protobuf:"bytes,1,rep,name=userURLs,proto3" json:"userURLs,omitempty"` // длинный адрес
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddrUserResponse) Reset() {
	*x = GetAddrUserResponse{}
	mi := &file_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddrUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddrUserResponse) ProtoMessage() {}

func (x *GetAddrUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddrUserResponse.ProtoReflect.Descriptor instead.
func (*GetAddrUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *GetAddrUserResponse) GetUserURLs() []*UserURLs {
	if x != nil {
		return x.UserURLs
	}
	return nil
}

type BatchURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrID        string                 `protobuf:"bytes,1,opt,name=corrID,proto3" json:"corrID,omitempty"`
	URL           string                 `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchURL) Reset() {
	*x = BatchURL{}
	mi := &file_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURL) ProtoMessage() {}

func (x *BatchURL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURL.ProtoReflect.Descriptor instead.
func (*BatchURL) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *BatchURL) GetCorrID() string {
	if x != nil {
		return x.CorrID
	}
	return ""
}

func (x *BatchURL) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type PostBatchRequset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchURL      []*BatchURL            `protobuf:"bytes,1,rep,name=batchURL,proto3" json:"batchURL,omitempty"` // адреса для сокращения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBatchRequset) Reset() {
	*x = PostBatchRequset{}
	mi := &file_proto_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBatchRequset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBatchRequset) ProtoMessage() {}

func (x *PostBatchRequset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBatchRequset.ProtoReflect.Descriptor instead.
func (*PostBatchRequset) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *PostBatchRequset) GetBatchURL() []*BatchURL {
	if x != nil {
		return x.BatchURL
	}
	return nil
}

type PostBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchURL      []*BatchURL            `protobuf:"bytes,1,rep,name=batchURL,proto3" json:"batchURL,omitempty"` // адрес для сокращения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBatchResponse) Reset() {
	*x = PostBatchResponse{}
	mi := &file_proto_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBatchResponse) ProtoMessage() {}

func (x *PostBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBatchResponse.ProtoReflect.Descriptor instead.
func (*PostBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *PostBatchResponse) GetBatchURL() []*BatchURL {
	if x != nil {
		return x.BatchURL
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{10}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{11}
}

type DeleteAddrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idents        []string               `protobuf:"bytes,1,rep,name=idents,proto3" json:"idents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddrRequest) Reset() {
	*x = DeleteAddrRequest{}
	mi := &file_proto_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddrRequest) ProtoMessage() {}

func (x *DeleteAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddrRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddrRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAddrRequest) GetIdents() []string {
	if x != nil {
		return x.Idents
	}
	return nil
}

type DeleteAddrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddrResponse) Reset() {
	*x = DeleteAddrResponse{}
	mi := &file_proto_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddrResponse) ProtoMessage() {}

func (x *DeleteAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddrResponse.ProtoReflect.Descriptor instead.
func (*DeleteAddrResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{13}
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{14}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumURLs       int64                  `protobuf:"varint,1,opt,name=numURLs,proto3" json:"numURLs,omitempty"`
	NumUsers      int64                  `protobuf:"varint,2,opt,name=numUsers,proto3" json:"numUsers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatsResponse) GetNumURLs() int64 {
	if x != nil {
		return x.NumURLs
	}
	return 0
}

func (x *GetStatsResponse) GetNumUsers() int64 {
	if x != nil {
		return x.NumUsers
	}
	return 0
}

var File_proto_shortener_proto protoreflect.FileDescriptor

const file_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x15proto/shortener.proto\x12\vprotoServer\")\n" +
	"\x0fPostAddrRequset\x12\x16\n" +
	"\x06addres\x18\x01 \x01(\tR\x06addres\"*\n" +
	"\x10PostAddrResponse\x12\x16\n" +
	"\x06addres\x18\x01 \x01(\tR\x06addres\".\n" +
	"\x0eGetAddrRequset\x12\x1c\n" +
	"\tshortAddr\x18\x01 \x01(\tR\tshortAddr\")\n" +
	"\x0fGetAddrResponse\x12\x16\n" +
	"\x06addres\x18\x01 \x01(\tR\x06addres\"@\n" +
	"\bUserURLs\x12\x18\n" +
	"\aorigURL\x18\x01 \x01(\tR\aorigURL\x12\x1a\n" +
	"\bshortURL\x18\x02 \x01(\tR\bshortURL\"\x14\n" +
	"\x12GetAddrUserRequset\"H\n" +
	"\x13GetAddrUserResponse\x121\n" +
	"\buserURLs\x18\x01 \x03(\v2\x15.protoServer.UserURLsR\buserURLs\"4\n" +
	"\bBatchURL\x12\x16\n" +
	"\x06corrID\x18\x01 \x01(\tR\x06corrID\x12\x10\n" +
	"\x03URL\x18\x02 \x01(\tR\x03URL\"E\n" +
	"\x10PostBatchRequset\x121\n" +
	"\bbatchURL\x18\x01 \x03(\v2\x15.protoServer.BatchURLR\bbatchURL\"F\n" +
	"\x11PostBatchResponse\x121\n" +
	"\bbatchURL\x18\x01 \x03(\v2\x15.protoServer.BatchURLR\bbatchURL\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"+\n" +
	"\x11DeleteAddrRequest\x12\x16\n" +
	"\x06idents\x18\x01 \x03(\tR\x06idents\"\x14\n" +
	"\x12DeleteAddrResponse\"\x11\n" +
	"\x0fGetStatsRequest\"H\n" +
	"\x10GetStatsResponse\x12\x18\n" +
	"\anumURLs\x18\x01 \x01(\x03R\anumURLs\x12\x1a\n" +
	"\bnumUsers\x18\x02 \x01(\x03R\bnumUsers2\x8d\x04\n" +
	"\tShortener\x12G\n" +
	"\bPostAddr\x12\x1c.protoServer.PostAddrRequset\x1a\x1d.protoServer.PostAddrResponse\x12D\n" +
	"\aGetAddr\x12\x1b.protoServer.GetAddrRequset\x1a\x1c.protoServer.GetAddrResponse\x12P\n" +
	"\vGetAddrUser\x12\x1f.protoServer.GetAddrUserRequset\x1a .protoServer.GetAddrUserResponse\x12J\n" +
	"\tPostBatch\x12\x1d.protoServer.PostBatchRequset\x1a\x1e.protoServer.PostBatchResponse\x12;\n" +
	"\x04Ping\x12\x18.protoServer.PingRequest\x1a\x19.protoServer.PingResponse\x12M\n" +
	"\n" +
	"DeleteAddr\x12\x1e.protoServer.DeleteAddrRequest\x1a\x1f.protoServer.DeleteAddrResponse\x12G\n" +
	"\bGetStats\x12\x1c.protoServer.GetStatsRequest\x1a\x1d.protoServer.GetStatsResponseB\x13Z\x11protoServer/protob\x06proto3"

var (
	file_proto_shortener_proto_rawDescOnce sync.Once
	file_proto_shortener_proto_rawDescData []byte
)

func file_proto_shortener_proto_rawDescGZIP() []byte {
	file_proto_shortener_proto_rawDescOnce.Do(func() {
		file_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)))
	})
	return file_proto_shortener_proto_rawDescData
}

var file_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_shortener_proto_goTypes = []any{
	(*PostAddrRequset)(nil),     // 0: protoServer.PostAddrRequset
	(*PostAddrResponse)(nil),    // 1: protoServer.PostAddrResponse
	(*GetAddrRequset)(nil),      // 2: protoServer.GetAddrRequset
	(*GetAddrResponse)(nil),     // 3: protoServer.GetAddrResponse
	(*UserURLs)(nil),            // 4: protoServer.UserURLs
	(*GetAddrUserRequset)(nil),  // 5: protoServer.GetAddrUserRequset
	(*GetAddrUserResponse)(nil), // 6: protoServer.GetAddrUserResponse
	(*BatchURL)(nil),            // 7: protoServer.BatchURL
	(*PostBatchRequset)(nil),    // 8: protoServer.PostBatchRequset
	(*PostBatchResponse)(nil),   // 9: protoServer.PostBatchResponse
	(*PingRequest)(nil),         // 10: protoServer.PingRequest
	(*PingResponse)(nil),        // 11: protoServer.PingResponse
	(*DeleteAddrRequest)(nil),   // 12: protoServer.DeleteAddrRequest
	(*DeleteAddrResponse)(nil),  // 13: protoServer.DeleteAddrResponse
	(*GetStatsRequest)(nil),     // 14: protoServer.GetStatsRequest
	(*GetStatsResponse)(nil),    // 15: protoServer.GetStatsResponse
}
var file_proto_shortener_proto_depIdxs = []int32{
	4,  // 0: protoServer.GetAddrUserResponse.userURLs:type_name -> protoServer.UserURLs
	7,  // 1: protoServer.PostBatchRequset.batchURL:type_name -> protoServer.BatchURL
	7,  // 2: protoServer.PostBatchResponse.batchURL:type_name -> protoServer.BatchURL
	0,  // 3: protoServer.Shortener.PostAddr:input_type -> protoServer.PostAddrRequset
	2,  // 4: protoServer.Shortener.GetAddr:input_type -> protoServer.GetAddrRequset
	5,  // 5: protoServer.Shortener.GetAddrUser:input_type -> protoServer.GetAddrUserRequset
	8,  // 6: protoServer.Shortener.PostBatch:input_type -> protoServer.PostBatchRequset
	10, // 7: protoServer.Shortener.Ping:input_type -> protoServer.PingRequest
	12, // 8: protoServer.Shortener.DeleteAddr:input_type -> protoServer.DeleteAddrRequest
	14, // 9: protoServer.Shortener.GetStats:input_type -> protoServer.GetStatsRequest
	1,  // 10: protoServer.Shortener.PostAddr:output_type -> protoServer.PostAddrResponse
	3,  // 11: protoServer.Shortener.GetAddr:output_type -> protoServer.GetAddrResponse
	6,  // 12: protoServer.Shortener.GetAddrUser:output_type -> protoServer.GetAddrUserResponse
	9,  // 13: protoServer.Shortener.PostBatch:output_type -> protoServer.PostBatchResponse
	11, // 14: protoServer.Shortener.Ping:output_type -> protoServer.PingResponse
	13, // 15: protoServer.Shortener.DeleteAddr:output_type -> protoServer.DeleteAddrResponse
	15, // 16: protoServer.Shortener.GetStats:output_type -> protoServer.GetStatsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_shortener_proto_init() }
func file_proto_shortener_proto_init() {
	if File_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortener_proto_goTypes,
		DependencyIndexes: file_proto_shortener_proto_depIdxs,
		MessageInfos:      file_proto_shortener_proto_msgTypes,
	}.Build()
	File_proto_shortener_proto = out.File
	file_proto_shortener_proto_goTypes = nil
	file_proto_shortener_proto_depIdxs = nil
}
