// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/storage/storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	json "encoding/json"
	reflect "reflect"

	models "github.com/Arti9991/shortener/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockStorFunc is a mock of StorFunc interface.
type MockStorFunc struct {
	ctrl     *gomock.Controller
	recorder *MockStorFuncMockRecorder
}

// MockStorFuncMockRecorder is the mock recorder for MockStorFunc.
type MockStorFuncMockRecorder struct {
	mock *MockStorFunc
}

// NewMockStorFunc creates a new mock instance.
func NewMockStorFunc(ctrl *gomock.Controller) *MockStorFunc {
	mock := &MockStorFunc{ctrl: ctrl}
	mock.recorder = &MockStorFuncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorFunc) EXPECT() *MockStorFuncMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStorFunc) Get(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorFuncMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorFunc)(nil).Get), arg0)
}

// GetOrig mocks base method.
func (m *MockStorFunc) GetOrig(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrig", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrig indicates an expected call of GetOrig.
func (mr *MockStorFuncMockRecorder) GetOrig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrig", reflect.TypeOf((*MockStorFunc)(nil).GetOrig), arg0)
}

// Ping mocks base method.
func (m *MockStorFunc) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStorFuncMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStorFunc)(nil).Ping))
}

// Save mocks base method.
func (m *MockStorFunc) Save(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStorFuncMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStorFunc)(nil).Save), arg0, arg1)
}

// SaveTx mocks base method.
func (m *MockStorFunc) SaveTx(arg0 *json.Decoder, arg1 string) (models.OutBuff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTx", arg0, arg1)
	ret0, _ := ret[0].(models.OutBuff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTx indicates an expected call of SaveTx.
func (mr *MockStorFuncMockRecorder) SaveTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTx", reflect.TypeOf((*MockStorFunc)(nil).SaveTx), arg0, arg1)
}
